apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

bases:
  - ../../base

namePrefix: staging-

patchesStrategicMerge:
  - rollout-patch.yaml
  - ingress-patch.yaml

images:
  - name: localhost:5001/demo-app-go
    newTag: v1.0.0

commonLabels:
  environment: staging
