apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-go
  labels:
    app: demo-app-go
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo.local
    secretName: demo-app-go-tls
  rules:
  - host: demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-app-go
            port:
              name: http
