apiVersion: v1
kind: Service
metadata:
  name: demo-app-go
  labels:
    app: demo-app-go
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: demo-app-go
---
# Service for canary/preview pods (used by Argo Rollouts)
apiVersion: v1
kind: Service
metadata:
  name: demo-app-go-canary
  labels:
    app: demo-app-go
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: demo-app-go
