apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-go
  labels:
    app: demo-app-go
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: demo-app-go
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
