apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
  - ../../base

patchesStrategicMerge:
  - rollout-patch.yaml

images:
  - name: localhost:5001/demo-app-go
    newTag: latest

commonLabels:
  environment: dev
